### PR TITLE
Implements Required changes for MQTT and Azure IoT

### PR DESCRIPTION
**Pull request by me-no-dev**
- WiFi state machine
- Multiple SNTP servers
- Better disconnect detection
- Faster reconnection

### CODE REVIEW

**Comment by ritazh** [comment]
Thank you for your contribution @me-no-dev !

For this PR, since it touches core files, please provide the following to speed up the review process:

- [ ] What issue or bug does this PR resolve or what feature does this PR add
- [ ] If it's an issue or a bug, please provide repro steps
- [ ] Please provide steps for how to test this PR

**Comment by me-no-dev** [comment]
Hello Rita, This is Hristo from Espressif. I think I have explained all that in the emails :)

**Comment by ritazh** [comment]
Hi @me-no-dev since this is all open source, let's keep all conversations here so that other developers can also reference this in the future. 

Since this PR touches the core logic of this solution, to test this PR, can you please provide specific steps on how to test this (for example, how long to wait before internet connection is restored).

**Comment by me-no-dev** [comment]
Oh Rita, I'm sorry. I thought this repository was used to work on the projects that we are involved in. Did not realize this is that sort of a public repository. You do not need those changes. They are Cevital and Brandt usage.

**Comment by ritazh** [comment]
@me-no-dev Do you think these changes can be helpful for other users and companies, if so then this should be merged. Also before you added these changes, were there noticeable issues/bugs? If so, please specify what they are in case other using this solution face the same issue.

**Pull request closed without merging**
